id: P5DFF55BB
initial_creation_type: input
source_metadata:
  title: Gyalwa Yangönpa
  language: en
  description: 'Texts by and about the famous Drukpa Kagyü adept Yangönpa Gyaltsen
    Pal (yang dgon pa rgyal mtshan dpal, 1213–1258):'
  volume:
    063d64a0e9b942589b65b4c46cb21a49:
      title: 'The Liberating Guide: A Prayer to Gyalwa Yangönpa'
      parent: Prayers
created_at: '2022-02-28T23:29:50.470247'
last_modified_at: '2022-02-28T23:29:50.470253'
